### Generate bikes
# First, generate some bikes
POST {{bike-sharing}}/bikes?bikes=10&bikeType=city
Accept: application/json

### List all
# Show available bikes
GET {{bike-sharing}}/bikes
Accept: application/json

### Checkout a Bike
# Checkout an available bike
PATCH {{bike-sharing}}/bikes/ac26b900-74e9-4e82-9812-c3c9a4899f84/checkout/brunch
Accept: application/json

### Check on bike
GET {{bike-sharing}}/bikes/ac26b900-74e9-4e82-9812-c3c9a4899f84
Accept: application/json

### Return a Bike
# return a bike
PATCH {{bike-sharing}}/bikes/ac26b900-74e9-4e82-9812-c3c9a4899f84/return/Toronto
Accept: application/json