### Generate bikes
# First, generate some bikes
POST {{bike-sharing}}/bikes?bikes=10&bikeType=city
Accept: application/json

### List all
# Show available bikes
GET {{bike-sharing}}/bikes
Accept: application/json

### Checkout a Bike
# Checkout an available bike
PATCH {{bike-sharing}}/bikes/ef3bb1e1-6d25-4215-a5b4-1503afdc1ea9/checkout/brunch
Accept: application/json

### Check on bike
# Attempt to checkout a bike that doesn't exist
GET {{bike-sharing}}/bikes/ef3bb1e1-6d25-4215-a5b4-1503afdc1ea9
Accept: application/json

### Return a Bike
# return a bike
PATCH {{bike-sharing}}/bikes/ef3bb1e1-6d25-4215-a5b4-1503afdc1ea9/return/Amsterdam
Accept: application/json